// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const count5xxSince = `-- name: Count5xxSince :one
SELECT COUNT(*) FROM requests WHERE status >= 500 AND ts >= ?
`

func (q *Queries) Count5xxSince(ctx context.Context, ts time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, count5xxSince, ts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAppErrorsSinceForAlert = `-- name: CountAppErrorsSinceForAlert :one
SELECT COUNT(*) FROM app_logs WHERE level IN ('ERROR', 'WARN') AND ts >= ?
`

func (q *Queries) CountAppErrorsSinceForAlert(ctx context.Context, ts time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAppErrorsSinceForAlert, ts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequestsInWindow = `-- name: CountRequestsInWindow :one
SELECT COUNT(*) FROM requests WHERE ts >= ?
`

func (q *Queries) CountRequestsInWindow(ctx context.Context, ts time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRequestsInWindow, ts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlertRule = `-- name: CreateAlertRule :exec
INSERT INTO alert_rules (name, type, threshold, window_minutes, cooldown_minutes)
VALUES (?, ?, ?, ?, ?)
`

type CreateAlertRuleParams struct {
	Name            string `json:"name"`
	Type            string `json:"type"`
	Threshold       int64  `json:"threshold"`
	WindowMinutes   int64  `json:"window_minutes"`
	CooldownMinutes int64  `json:"cooldown_minutes"`
}

func (q *Queries) CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) error {
	_, err := q.db.ExecContext(ctx, createAlertRule,
		arg.Name,
		arg.Type,
		arg.Threshold,
		arg.WindowMinutes,
		arg.CooldownMinutes,
	)
	return err
}

const deleteAlertLogsBefore = `-- name: DeleteAlertLogsBefore :exec
DELETE FROM alert_log WHERE created_at < ?
`

func (q *Queries) DeleteAlertLogsBefore(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteAlertLogsBefore, createdAt)
	return err
}

const deleteAlertRule = `-- name: DeleteAlertRule :exec
DELETE FROM alert_rules WHERE id = ?
`

func (q *Queries) DeleteAlertRule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAlertRule, id)
	return err
}

const insertAlertLog = `-- name: InsertAlertLog :exec
INSERT INTO alert_log (rule_id, type, message, details) VALUES (?, ?, ?, ?)
`

type InsertAlertLogParams struct {
	RuleID  int64  `json:"rule_id"`
	Type    string `json:"type"`
	Message string `json:"message"`
	Details string `json:"details"`
}

func (q *Queries) InsertAlertLog(ctx context.Context, arg InsertAlertLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAlertLog,
		arg.RuleID,
		arg.Type,
		arg.Message,
		arg.Details,
	)
	return err
}

const listAlertRules = `-- name: ListAlertRules :many
SELECT id, name, type, enabled, threshold, window_minutes, cooldown_minutes, last_fired_at, created_at
FROM alert_rules ORDER BY type, name
`

func (q *Queries) ListAlertRules(ctx context.Context) ([]AlertRule, error) {
	rows, err := q.db.QueryContext(ctx, listAlertRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertRule
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.Threshold,
			&i.WindowMinutes,
			&i.CooldownMinutes,
			&i.LastFiredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAlertRules = `-- name: ListEnabledAlertRules :many
SELECT id, name, type, enabled, threshold, window_minutes, cooldown_minutes, last_fired_at
FROM alert_rules WHERE enabled = 1
`

type ListEnabledAlertRulesRow struct {
	ID              int64        `json:"id"`
	Name            string       `json:"name"`
	Type            string       `json:"type"`
	Enabled         int64        `json:"enabled"`
	Threshold       int64        `json:"threshold"`
	WindowMinutes   int64        `json:"window_minutes"`
	CooldownMinutes int64        `json:"cooldown_minutes"`
	LastFiredAt     sql.NullTime `json:"last_fired_at"`
}

func (q *Queries) ListEnabledAlertRules(ctx context.Context) ([]ListEnabledAlertRulesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledAlertRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledAlertRulesRow
	for rows.Next() {
		var i ListEnabledAlertRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.Threshold,
			&i.WindowMinutes,
			&i.CooldownMinutes,
			&i.LastFiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentAlertLogs = `-- name: RecentAlertLogs :many
SELECT id, rule_id, type, message, details, created_at
FROM alert_log ORDER BY id DESC LIMIT ?
`

func (q *Queries) RecentAlertLogs(ctx context.Context, limit int64) ([]AlertLog, error) {
	rows, err := q.db.QueryContext(ctx, recentAlertLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertLog
	for rows.Next() {
		var i AlertLog
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.Type,
			&i.Message,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleAlertRule = `-- name: ToggleAlertRule :exec
UPDATE alert_rules SET enabled = CASE WHEN enabled = 0 THEN 1 ELSE 0 END WHERE id = ?
`

func (q *Queries) ToggleAlertRule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, toggleAlertRule, id)
	return err
}

const updateAlertRuleFired = `-- name: UpdateAlertRuleFired :exec
UPDATE alert_rules SET last_fired_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) UpdateAlertRuleFired(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateAlertRuleFired, id)
	return err
}
