// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: anomalies.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const acknowledgeAnomaly = `-- name: AcknowledgeAnomaly :exec
UPDATE anomalies SET acknowledged = 1 WHERE id = ?
`

func (q *Queries) AcknowledgeAnomaly(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, acknowledgeAnomaly, id)
	return err
}

const countUnacknowledgedAnomalies = `-- name: CountUnacknowledgedAnomalies :one
SELECT COUNT(*) FROM anomalies WHERE acknowledged = 0
`

func (q *Queries) CountUnacknowledgedAnomalies(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnacknowledgedAnomalies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAnomaliesBefore = `-- name: DeleteAnomaliesBefore :exec
DELETE FROM anomalies WHERE ts < ?
`

func (q *Queries) DeleteAnomaliesBefore(ctx context.Context, ts time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteAnomaliesBefore, ts)
	return err
}

const hourlyErrorRates = `-- name: HourlyErrorRates :many
SELECT strftime('%Y-%m-%d %H:00', ts) AS hour,
       COUNT(*) AS total,
       SUM(CASE WHEN status >= 500 THEN 1 ELSE 0 END) AS count_5xx
FROM requests WHERE ts >= ?
GROUP BY hour ORDER BY hour
`

type HourlyErrorRatesRow struct {
	Hour     interface{}     `json:"hour"`
	Total    int64           `json:"total"`
	Count5xx sql.NullFloat64 `json:"count_5xx"`
}

func (q *Queries) HourlyErrorRates(ctx context.Context, ts time.Time) ([]HourlyErrorRatesRow, error) {
	rows, err := q.db.QueryContext(ctx, hourlyErrorRates, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HourlyErrorRatesRow
	for rows.Next() {
		var i HourlyErrorRatesRow
		if err := rows.Scan(&i.Hour, &i.Total, &i.Count5xx); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const iPErrorRate = `-- name: IPErrorRate :many
SELECT client_ip,
    COUNT(*) AS total,
    SUM(CASE WHEN status >= 400 AND status < 500 THEN 1 ELSE 0 END) AS count_4xx
FROM requests WHERE ts >= ?
GROUP BY client_ip
HAVING COUNT(*) >= 10
ORDER BY total DESC
`

type IPErrorRateRow struct {
	ClientIp string          `json:"client_ip"`
	Total    int64           `json:"total"`
	Count4xx sql.NullFloat64 `json:"count_4xx"`
}

func (q *Queries) IPErrorRate(ctx context.Context, ts time.Time) ([]IPErrorRateRow, error) {
	rows, err := q.db.QueryContext(ctx, iPErrorRate, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IPErrorRateRow
	for rows.Next() {
		var i IPErrorRateRow
		if err := rows.Scan(&i.ClientIp, &i.Total, &i.Count4xx); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const iPRequestRateRecent = `-- name: IPRequestRateRecent :many
SELECT client_ip, COUNT(*) AS cnt
FROM requests WHERE ts >= ?1
GROUP BY client_ip
HAVING COUNT(*) >= ?2
ORDER BY COUNT(*) DESC
`

type IPRequestRateRecentParams struct {
	Since    time.Time   `json:"since"`
	MinCount interface{} `json:"min_count"`
}

type IPRequestRateRecentRow struct {
	ClientIp string `json:"client_ip"`
	Cnt      int64  `json:"cnt"`
}

func (q *Queries) IPRequestRateRecent(ctx context.Context, arg IPRequestRateRecentParams) ([]IPRequestRateRecentRow, error) {
	rows, err := q.db.QueryContext(ctx, iPRequestRateRecent, arg.Since, arg.MinCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IPRequestRateRecentRow
	for rows.Next() {
		var i IPRequestRateRecentRow
		if err := rows.Scan(&i.ClientIp, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAnomaly = `-- name: InsertAnomaly :exec
INSERT INTO anomalies (ts, type, client_ip, host, description, score) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAnomalyParams struct {
	Ts          time.Time `json:"ts"`
	Type        string    `json:"type"`
	ClientIp    string    `json:"client_ip"`
	Host        string    `json:"host"`
	Description string    `json:"description"`
	Score       float64   `json:"score"`
}

func (q *Queries) InsertAnomaly(ctx context.Context, arg InsertAnomalyParams) error {
	_, err := q.db.ExecContext(ctx, insertAnomaly,
		arg.Ts,
		arg.Type,
		arg.ClientIp,
		arg.Host,
		arg.Description,
		arg.Score,
	)
	return err
}

const recentAnomalies = `-- name: RecentAnomalies :many
SELECT id, ts, type, client_ip, host, description, score, acknowledged, created_at
FROM anomalies ORDER BY id DESC LIMIT ?
`

func (q *Queries) RecentAnomalies(ctx context.Context, limit int64) ([]Anomaly, error) {
	rows, err := q.db.QueryContext(ctx, recentAnomalies, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Anomaly
	for rows.Next() {
		var i Anomaly
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Type,
			&i.ClientIp,
			&i.Host,
			&i.Description,
			&i.Score,
			&i.Acknowledged,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
