// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_logs.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countAppErrorsSince = `-- name: CountAppErrorsSince :one
SELECT COUNT(*) FROM app_logs WHERE level = 'ERROR' AND ts >= ?
`

func (q *Queries) CountAppErrorsSince(ctx context.Context, ts time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAppErrorsSince, ts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAppLogsSince = `-- name: CountAppLogsSince :one
SELECT COUNT(*) FROM app_logs WHERE ts >= ?
`

func (q *Queries) CountAppLogsSince(ctx context.Context, ts time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAppLogsSince, ts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAppLogsBeforeBatch = `-- name: DeleteAppLogsBeforeBatch :execresult
DELETE FROM app_logs WHERE id IN (
    SELECT al.id FROM app_logs al
    WHERE (al.level = 'ERROR' AND al.ts < ?1)
       OR (al.level <> 'ERROR' AND al.ts < ?2)
    ORDER BY al.id LIMIT ?3
)
`

type DeleteAppLogsBeforeBatchParams struct {
	ErrorCutoff time.Time `json:"error_cutoff"`
	OtherCutoff time.Time `json:"other_cutoff"`
	BatchSize   int64     `json:"batch_size"`
}

// Level-aware retention: ERROR is rare and worth keeping, but the table is
// overwhelmingly WARN/INFO noise, so those get a much shorter horizon.
func (q *Queries) DeleteAppLogsBeforeBatch(ctx context.Context, arg DeleteAppLogsBeforeBatchParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAppLogsBeforeBatch, arg.ErrorCutoff, arg.OtherCutoff, arg.BatchSize)
}

const getAppLog = `-- name: GetAppLog :one
SELECT id, ts, app, level, message, attrs, source, created_at
FROM app_logs
WHERE id = ?
`

func (q *Queries) GetAppLog(ctx context.Context, id int64) (AppLog, error) {
	row := q.db.QueryRowContext(ctx, getAppLog, id)
	var i AppLog
	err := row.Scan(
		&i.ID,
		&i.Ts,
		&i.App,
		&i.Level,
		&i.Message,
		&i.Attrs,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const insertAppLog = `-- name: InsertAppLog :exec
INSERT INTO app_logs (ts, app, level, message, attrs, source)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAppLogParams struct {
	Ts      time.Time `json:"ts"`
	App     string    `json:"app"`
	Level   string    `json:"level"`
	Message string    `json:"message"`
	Attrs   string    `json:"attrs"`
	Source  string    `json:"source"`
}

func (q *Queries) InsertAppLog(ctx context.Context, arg InsertAppLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAppLog,
		arg.Ts,
		arg.App,
		arg.Level,
		arg.Message,
		arg.Attrs,
		arg.Source,
	)
	return err
}

const recentAppErrors = `-- name: RecentAppErrors :many
SELECT id, ts, app, level, message, attrs, source, created_at
FROM app_logs
WHERE level IN ('ERROR', 'WARN')
ORDER BY ts DESC, id DESC
LIMIT ?
`

func (q *Queries) RecentAppErrors(ctx context.Context, limit int64) ([]AppLog, error) {
	rows, err := q.db.QueryContext(ctx, recentAppErrors, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppLog
	for rows.Next() {
		var i AppLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.App,
			&i.Level,
			&i.Message,
			&i.Attrs,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
