// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_logs.sql

package db

import (
	"context"
	"time"
)

const appList = `-- name: AppList :many
SELECT DISTINCT app FROM app_logs ORDER BY app
`

func (q *Queries) AppList(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, appList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var app string
		if err := rows.Scan(&app); err != nil {
			return nil, err
		}
		items = append(items, app)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAppErrorsSince = `-- name: CountAppErrorsSince :one
SELECT COUNT(*) FROM app_logs WHERE level = 'ERROR' AND ts >= ?
`

func (q *Queries) CountAppErrorsSince(ctx context.Context, ts time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAppErrorsSince, ts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAppLogsSince = `-- name: CountAppLogsSince :one
SELECT COUNT(*) FROM app_logs WHERE ts >= ?
`

func (q *Queries) CountAppLogsSince(ctx context.Context, ts time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAppLogsSince, ts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAppLogsBefore = `-- name: DeleteAppLogsBefore :exec
DELETE FROM app_logs WHERE ts < ?
`

func (q *Queries) DeleteAppLogsBefore(ctx context.Context, ts time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteAppLogsBefore, ts)
	return err
}

const getAppLog = `-- name: GetAppLog :one
SELECT id, ts, app, level, message, attrs, source, created_at
FROM app_logs
WHERE id = ?
`

func (q *Queries) GetAppLog(ctx context.Context, id int64) (AppLog, error) {
	row := q.db.QueryRowContext(ctx, getAppLog, id)
	var i AppLog
	err := row.Scan(
		&i.ID,
		&i.Ts,
		&i.App,
		&i.Level,
		&i.Message,
		&i.Attrs,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const insertAppLog = `-- name: InsertAppLog :exec
INSERT INTO app_logs (ts, app, level, message, attrs, source)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAppLogParams struct {
	Ts      time.Time `json:"ts"`
	App     string    `json:"app"`
	Level   string    `json:"level"`
	Message string    `json:"message"`
	Attrs   string    `json:"attrs"`
	Source  string    `json:"source"`
}

func (q *Queries) InsertAppLog(ctx context.Context, arg InsertAppLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAppLog,
		arg.Ts,
		arg.App,
		arg.Level,
		arg.Message,
		arg.Attrs,
		arg.Source,
	)
	return err
}

const recentAppErrors = `-- name: RecentAppErrors :many
SELECT id, ts, app, level, message, attrs, source, created_at
FROM app_logs
WHERE level IN ('ERROR', 'WARN')
ORDER BY id DESC
LIMIT ?
`

func (q *Queries) RecentAppErrors(ctx context.Context, limit int64) ([]AppLog, error) {
	rows, err := q.db.QueryContext(ctx, recentAppErrors, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppLog
	for rows.Next() {
		var i AppLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.App,
			&i.Level,
			&i.Message,
			&i.Attrs,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentAppLogs = `-- name: RecentAppLogs :many
SELECT id, ts, app, level, message, attrs, source, created_at
FROM app_logs
ORDER BY id DESC
LIMIT ?
`

func (q *Queries) RecentAppLogs(ctx context.Context, limit int64) ([]AppLog, error) {
	rows, err := q.db.QueryContext(ctx, recentAppLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppLog
	for rows.Next() {
		var i AppLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.App,
			&i.Level,
			&i.Message,
			&i.Attrs,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
