// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: autoblock.sql

package db

import (
	"context"
)

const createAutoblockRule = `-- name: CreateAutoblockRule :exec
INSERT OR IGNORE INTO autoblock_rules (pattern, description) VALUES (?, ?)
`

type CreateAutoblockRuleParams struct {
	Pattern     string `json:"pattern"`
	Description string `json:"description"`
}

func (q *Queries) CreateAutoblockRule(ctx context.Context, arg CreateAutoblockRuleParams) error {
	_, err := q.db.ExecContext(ctx, createAutoblockRule, arg.Pattern, arg.Description)
	return err
}

const deleteAutoblockRule = `-- name: DeleteAutoblockRule :exec
DELETE FROM autoblock_rules WHERE id = ?
`

func (q *Queries) DeleteAutoblockRule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAutoblockRule, id)
	return err
}

const incrementAutoblockHit = `-- name: IncrementAutoblockHit :exec
UPDATE autoblock_rules SET hit_count = hit_count + 1, last_hit_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) IncrementAutoblockHit(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementAutoblockHit, id)
	return err
}

const listAutoblockRules = `-- name: ListAutoblockRules :many
SELECT id, pattern, description, enabled, hit_count, last_hit_at, created_at
FROM autoblock_rules ORDER BY hit_count DESC, created_at
`

func (q *Queries) ListAutoblockRules(ctx context.Context) ([]AutoblockRule, error) {
	rows, err := q.db.QueryContext(ctx, listAutoblockRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutoblockRule
	for rows.Next() {
		var i AutoblockRule
		if err := rows.Scan(
			&i.ID,
			&i.Pattern,
			&i.Description,
			&i.Enabled,
			&i.HitCount,
			&i.LastHitAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAutoblockRules = `-- name: ListEnabledAutoblockRules :many
SELECT id, pattern, description FROM autoblock_rules WHERE enabled = 1
`

type ListEnabledAutoblockRulesRow struct {
	ID          int64  `json:"id"`
	Pattern     string `json:"pattern"`
	Description string `json:"description"`
}

func (q *Queries) ListEnabledAutoblockRules(ctx context.Context) ([]ListEnabledAutoblockRulesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledAutoblockRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledAutoblockRulesRow
	for rows.Next() {
		var i ListEnabledAutoblockRulesRow
		if err := rows.Scan(&i.ID, &i.Pattern, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleAutoblockRule = `-- name: ToggleAutoblockRule :exec
UPDATE autoblock_rules SET enabled = CASE WHEN enabled = 0 THEN 1 ELSE 0 END WHERE id = ?
`

func (q *Queries) ToggleAutoblockRule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, toggleAutoblockRule, id)
	return err
}
