// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bots.sql

package db

import (
	"context"
)

const createBotPattern = `-- name: CreateBotPattern :exec
INSERT INTO bot_patterns (pattern, label) VALUES (?, ?)
`

type CreateBotPatternParams struct {
	Pattern string `json:"pattern"`
	Label   string `json:"label"`
}

func (q *Queries) CreateBotPattern(ctx context.Context, arg CreateBotPatternParams) error {
	_, err := q.db.ExecContext(ctx, createBotPattern, arg.Pattern, arg.Label)
	return err
}

const deleteBotPattern = `-- name: DeleteBotPattern :exec
DELETE FROM bot_patterns WHERE id = ?
`

func (q *Queries) DeleteBotPattern(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBotPattern, id)
	return err
}

const listBotPatterns = `-- name: ListBotPatterns :many
SELECT id, pattern, label, created_at FROM bot_patterns ORDER BY label
`

func (q *Queries) ListBotPatterns(ctx context.Context) ([]BotPattern, error) {
	rows, err := q.db.QueryContext(ctx, listBotPatterns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotPattern
	for rows.Next() {
		var i BotPattern
		if err := rows.Scan(
			&i.ID,
			&i.Pattern,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
