// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bots.sql

package db

import (
	"context"
)

const createBotPattern = `-- name: CreateBotPattern :exec
INSERT INTO bot_patterns (pattern, label, block) VALUES (?, ?, ?)
`

type CreateBotPatternParams struct {
	Pattern string `json:"pattern"`
	Label   string `json:"label"`
	Block   int64  `json:"block"`
}

func (q *Queries) CreateBotPattern(ctx context.Context, arg CreateBotPatternParams) error {
	_, err := q.db.ExecContext(ctx, createBotPattern, arg.Pattern, arg.Label, arg.Block)
	return err
}

const deleteBotPattern = `-- name: DeleteBotPattern :exec
DELETE FROM bot_patterns WHERE id = ?
`

func (q *Queries) DeleteBotPattern(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBotPattern, id)
	return err
}

const getBotPattern = `-- name: GetBotPattern :one
SELECT id, pattern, label, block, created_at FROM bot_patterns WHERE id = ?
`

func (q *Queries) GetBotPattern(ctx context.Context, id int64) (BotPattern, error) {
	row := q.db.QueryRowContext(ctx, getBotPattern, id)
	var i BotPattern
	err := row.Scan(
		&i.ID,
		&i.Pattern,
		&i.Label,
		&i.Block,
		&i.CreatedAt,
	)
	return i, err
}

const listBotPatterns = `-- name: ListBotPatterns :many
SELECT id, pattern, label, block, created_at FROM bot_patterns ORDER BY label
`

func (q *Queries) ListBotPatterns(ctx context.Context) ([]BotPattern, error) {
	rows, err := q.db.QueryContext(ctx, listBotPatterns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotPattern
	for rows.Next() {
		var i BotPattern
		if err := rows.Scan(
			&i.ID,
			&i.Pattern,
			&i.Label,
			&i.Block,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleBotBlock = `-- name: ToggleBotBlock :exec
UPDATE bot_patterns SET block = CASE WHEN block = 0 THEN 1 ELSE 0 END WHERE id = ?
`

func (q *Queries) ToggleBotBlock(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, toggleBotBlock, id)
	return err
}
