// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: honeypots.sql

package db

import (
	"context"
)

const createHoneypot = `-- name: CreateHoneypot :exec
INSERT OR IGNORE INTO honeypots (path, description) VALUES (?, ?)
`

type CreateHoneypotParams struct {
	Path        string `json:"path"`
	Description string `json:"description"`
}

func (q *Queries) CreateHoneypot(ctx context.Context, arg CreateHoneypotParams) error {
	_, err := q.db.ExecContext(ctx, createHoneypot, arg.Path, arg.Description)
	return err
}

const deleteHoneypot = `-- name: DeleteHoneypot :exec
DELETE FROM honeypots WHERE id = ?
`

func (q *Queries) DeleteHoneypot(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteHoneypot, id)
	return err
}

const incrementHoneypotHit = `-- name: IncrementHoneypotHit :exec
UPDATE honeypots SET hit_count = hit_count + 1, last_hit_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) IncrementHoneypotHit(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementHoneypotHit, id)
	return err
}

const listEnabledHoneypots = `-- name: ListEnabledHoneypots :many
SELECT id, path, description FROM honeypots WHERE enabled = 1
`

type ListEnabledHoneypotsRow struct {
	ID          int64  `json:"id"`
	Path        string `json:"path"`
	Description string `json:"description"`
}

func (q *Queries) ListEnabledHoneypots(ctx context.Context) ([]ListEnabledHoneypotsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledHoneypots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledHoneypotsRow
	for rows.Next() {
		var i ListEnabledHoneypotsRow
		if err := rows.Scan(&i.ID, &i.Path, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHoneypots = `-- name: ListHoneypots :many
SELECT id, path, description, enabled, hit_count, last_hit_at, created_at
FROM honeypots ORDER BY hit_count DESC, created_at
`

func (q *Queries) ListHoneypots(ctx context.Context) ([]Honeypot, error) {
	rows, err := q.db.QueryContext(ctx, listHoneypots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Honeypot
	for rows.Next() {
		var i Honeypot
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Description,
			&i.Enabled,
			&i.HitCount,
			&i.LastHitAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleHoneypot = `-- name: ToggleHoneypot :exec
UPDATE honeypots SET enabled = CASE WHEN enabled = 0 THEN 1 ELSE 0 END WHERE id = ?
`

func (q *Queries) ToggleHoneypot(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, toggleHoneypot, id)
	return err
}
