// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ips.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createBlockedIP = `-- name: CreateBlockedIP :exec
INSERT OR IGNORE INTO blocked_ips (ip, reason) VALUES (?, ?)
`

type CreateBlockedIPParams struct {
	Ip     string `json:"ip"`
	Reason string `json:"reason"`
}

func (q *Queries) CreateBlockedIP(ctx context.Context, arg CreateBlockedIPParams) error {
	_, err := q.db.ExecContext(ctx, createBlockedIP, arg.Ip, arg.Reason)
	return err
}

const deleteBlockedIP = `-- name: DeleteBlockedIP :exec
DELETE FROM blocked_ips WHERE id = ?
`

func (q *Queries) DeleteBlockedIP(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBlockedIP, id)
	return err
}

const isIPBlocked = `-- name: IsIPBlocked :one
SELECT COUNT(*) FROM blocked_ips WHERE ip = ?
`

func (q *Queries) IsIPBlocked(ctx context.Context, ip string) (int64, error) {
	row := q.db.QueryRowContext(ctx, isIPBlocked, ip)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listBlockedIPs = `-- name: ListBlockedIPs :many
SELECT id, ip, reason, created_at FROM blocked_ips ORDER BY created_at DESC
`

func (q *Queries) ListBlockedIPs(ctx context.Context) ([]BlockedIp, error) {
	rows, err := q.db.QueryContext(ctx, listBlockedIPs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlockedIp
	for rows.Next() {
		var i BlockedIp
		if err := rows.Scan(
			&i.ID,
			&i.Ip,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAutoBlockedIPs = `-- name: PruneAutoBlockedIPs :execresult
DELETE FROM blocked_ips
WHERE (reason LIKE 'auto-blocked:%' OR reason LIKE 'honeypot:%')
AND created_at < ?
`

func (q *Queries) PruneAutoBlockedIPs(ctx context.Context, createdAt time.Time) (sql.Result, error) {
	return q.db.ExecContext(ctx, pruneAutoBlockedIPs, createdAt)
}
