// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type BlockedIp struct {
	ID        int64     `json:"id"`
	Ip        string    `json:"ip"`
	Reason    string    `json:"reason"`
	CreatedAt time.Time `json:"created_at"`
}

type BotPattern struct {
	ID        int64     `json:"id"`
	Pattern   string    `json:"pattern"`
	Label     string    `json:"label"`
	Block     int64     `json:"block"`
	CreatedAt time.Time `json:"created_at"`
}

type Request struct {
	ID         int64     `json:"id"`
	Ts         time.Time `json:"ts"`
	Host       string    `json:"host"`
	ClientIp   string    `json:"client_ip"`
	Method     string    `json:"method"`
	Uri        string    `json:"uri"`
	Status     int64     `json:"status"`
	Size       int64     `json:"size"`
	UserAgent  string    `json:"user_agent"`
	DurationMs float64   `json:"duration_ms"`
	IsBot      int64     `json:"is_bot"`
}
