// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package db

import (
	"context"
	"time"
)

const countBotRequestsSince = `-- name: CountBotRequestsSince :one
SELECT COUNT(*) FROM requests WHERE ts >= ? AND is_bot = 1
`

func (q *Queries) CountBotRequestsSince(ctx context.Context, ts time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBotRequestsSince, ts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequests = `-- name: CountRequests :one
SELECT COUNT(*) FROM requests
`

func (q *Queries) CountRequests(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRequests)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequestsSince = `-- name: CountRequestsSince :one
SELECT COUNT(*) FROM requests WHERE ts >= ?
`

func (q *Queries) CountRequestsSince(ctx context.Context, ts time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRequestsSince, ts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUniqueIPsSince = `-- name: CountUniqueIPsSince :one
SELECT COUNT(DISTINCT client_ip) FROM requests WHERE ts >= ?
`

func (q *Queries) CountUniqueIPsSince(ctx context.Context, ts time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUniqueIPsSince, ts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRequestsBefore = `-- name: DeleteRequestsBefore :exec
DELETE FROM requests WHERE ts < ?
`

func (q *Queries) DeleteRequestsBefore(ctx context.Context, ts time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteRequestsBefore, ts)
	return err
}

const distinctHosts = `-- name: DistinctHosts :many
SELECT DISTINCT host FROM requests WHERE ts >= ? ORDER BY host
`

func (q *Queries) DistinctHosts(ctx context.Context, ts time.Time) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, distinctHosts, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var host string
		if err := rows.Scan(&host); err != nil {
			return nil, err
		}
		items = append(items, host)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRequest = `-- name: InsertRequest :exec
INSERT INTO requests (ts, host, client_ip, method, uri, status, size, user_agent, duration_ms, is_bot, country, city, referer)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertRequestParams struct {
	Ts         time.Time `json:"ts"`
	Host       string    `json:"host"`
	ClientIp   string    `json:"client_ip"`
	Method     string    `json:"method"`
	Uri        string    `json:"uri"`
	Status     int64     `json:"status"`
	Size       int64     `json:"size"`
	UserAgent  string    `json:"user_agent"`
	DurationMs float64   `json:"duration_ms"`
	IsBot      int64     `json:"is_bot"`
	Country    string    `json:"country"`
	City       string    `json:"city"`
	Referer    string    `json:"referer"`
}

func (q *Queries) InsertRequest(ctx context.Context, arg InsertRequestParams) error {
	_, err := q.db.ExecContext(ctx, insertRequest,
		arg.Ts,
		arg.Host,
		arg.ClientIp,
		arg.Method,
		arg.Uri,
		arg.Status,
		arg.Size,
		arg.UserAgent,
		arg.DurationMs,
		arg.IsBot,
		arg.Country,
		arg.City,
		arg.Referer,
	)
	return err
}

const recentRequests = `-- name: RecentRequests :many
SELECT id, ts, host, client_ip, method, uri, status, size, user_agent, duration_ms, is_bot, referer
FROM requests ORDER BY id DESC LIMIT ?
`

type RecentRequestsRow struct {
	ID         int64     `json:"id"`
	Ts         time.Time `json:"ts"`
	Host       string    `json:"host"`
	ClientIp   string    `json:"client_ip"`
	Method     string    `json:"method"`
	Uri        string    `json:"uri"`
	Status     int64     `json:"status"`
	Size       int64     `json:"size"`
	UserAgent  string    `json:"user_agent"`
	DurationMs float64   `json:"duration_ms"`
	IsBot      int64     `json:"is_bot"`
	Referer    string    `json:"referer"`
}

func (q *Queries) RecentRequests(ctx context.Context, limit int64) ([]RecentRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, recentRequests, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentRequestsRow
	for rows.Next() {
		var i RecentRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Host,
			&i.ClientIp,
			&i.Method,
			&i.Uri,
			&i.Status,
			&i.Size,
			&i.UserAgent,
			&i.DurationMs,
			&i.IsBot,
			&i.Referer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentRequestsSince = `-- name: RecentRequestsSince :many
SELECT id, ts, host, client_ip, method, uri, status, size, user_agent, duration_ms, is_bot, referer
FROM requests WHERE ts >= ? ORDER BY id DESC LIMIT ?
`

type RecentRequestsSinceParams struct {
	Ts    time.Time `json:"ts"`
	Limit int64     `json:"limit"`
}

type RecentRequestsSinceRow struct {
	ID         int64     `json:"id"`
	Ts         time.Time `json:"ts"`
	Host       string    `json:"host"`
	ClientIp   string    `json:"client_ip"`
	Method     string    `json:"method"`
	Uri        string    `json:"uri"`
	Status     int64     `json:"status"`
	Size       int64     `json:"size"`
	UserAgent  string    `json:"user_agent"`
	DurationMs float64   `json:"duration_ms"`
	IsBot      int64     `json:"is_bot"`
	Referer    string    `json:"referer"`
}

func (q *Queries) RecentRequestsSince(ctx context.Context, arg RecentRequestsSinceParams) ([]RecentRequestsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, recentRequestsSince, arg.Ts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentRequestsSinceRow
	for rows.Next() {
		var i RecentRequestsSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Host,
			&i.ClientIp,
			&i.Method,
			&i.Uri,
			&i.Status,
			&i.Size,
			&i.UserAgent,
			&i.DurationMs,
			&i.IsBot,
			&i.Referer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const referrerRequestsByHost = `-- name: ReferrerRequestsByHost :many
SELECT id, ts, host, client_ip, method, uri, status, user_agent, referer
FROM requests
WHERE ts >= ?1
  AND referer != ''
  AND (?2 = '' OR host = ?2)
ORDER BY id DESC LIMIT ?3
`

type ReferrerRequestsByHostParams struct {
	Since      time.Time   `json:"since"`
	HostFilter interface{} `json:"host_filter"`
	Lim        int64       `json:"lim"`
}

type ReferrerRequestsByHostRow struct {
	ID        int64     `json:"id"`
	Ts        time.Time `json:"ts"`
	Host      string    `json:"host"`
	ClientIp  string    `json:"client_ip"`
	Method    string    `json:"method"`
	Uri       string    `json:"uri"`
	Status    int64     `json:"status"`
	UserAgent string    `json:"user_agent"`
	Referer   string    `json:"referer"`
}

func (q *Queries) ReferrerRequestsByHost(ctx context.Context, arg ReferrerRequestsByHostParams) ([]ReferrerRequestsByHostRow, error) {
	rows, err := q.db.QueryContext(ctx, referrerRequestsByHost, arg.Since, arg.HostFilter, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReferrerRequestsByHostRow
	for rows.Next() {
		var i ReferrerRequestsByHostRow
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Host,
			&i.ClientIp,
			&i.Method,
			&i.Uri,
			&i.Status,
			&i.UserAgent,
			&i.Referer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const referrersByHost = `-- name: ReferrersByHost :many
SELECT referer, COUNT(*) AS cnt
FROM requests
WHERE ts >= ?1
  AND referer != ''
  AND (?2 = '' OR host = ?2)
GROUP BY referer ORDER BY cnt DESC LIMIT ?3
`

type ReferrersByHostParams struct {
	Since      time.Time   `json:"since"`
	HostFilter interface{} `json:"host_filter"`
	Lim        int64       `json:"lim"`
}

type ReferrersByHostRow struct {
	Referer string `json:"referer"`
	Cnt     int64  `json:"cnt"`
}

func (q *Queries) ReferrersByHost(ctx context.Context, arg ReferrersByHostParams) ([]ReferrersByHostRow, error) {
	rows, err := q.db.QueryContext(ctx, referrersByHost, arg.Since, arg.HostFilter, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReferrersByHostRow
	for rows.Next() {
		var i ReferrersByHostRow
		if err := rows.Scan(&i.Referer, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestsByHostSince = `-- name: RequestsByHostSince :many
SELECT host, COUNT(*) AS cnt
FROM requests WHERE ts >= ?
GROUP BY host ORDER BY cnt DESC
`

type RequestsByHostSinceRow struct {
	Host string `json:"host"`
	Cnt  int64  `json:"cnt"`
}

func (q *Queries) RequestsByHostSince(ctx context.Context, ts time.Time) ([]RequestsByHostSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, requestsByHostSince, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequestsByHostSinceRow
	for rows.Next() {
		var i RequestsByHostSinceRow
		if err := rows.Scan(&i.Host, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statusCodesSince = `-- name: StatusCodesSince :many
SELECT status, COUNT(*) AS cnt
FROM requests WHERE ts >= ?
GROUP BY status ORDER BY status
`

type StatusCodesSinceRow struct {
	Status int64 `json:"status"`
	Cnt    int64 `json:"cnt"`
}

func (q *Queries) StatusCodesSince(ctx context.Context, ts time.Time) ([]StatusCodesSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, statusCodesSince, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatusCodesSinceRow
	for rows.Next() {
		var i StatusCodesSinceRow
		if err := rows.Scan(&i.Status, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topIPsSince = `-- name: TopIPsSince :many
SELECT client_ip, COUNT(*) AS cnt
FROM requests WHERE ts >= ?
GROUP BY client_ip ORDER BY cnt DESC LIMIT ?
`

type TopIPsSinceParams struct {
	Ts    time.Time `json:"ts"`
	Limit int64     `json:"limit"`
}

type TopIPsSinceRow struct {
	ClientIp string `json:"client_ip"`
	Cnt      int64  `json:"cnt"`
}

func (q *Queries) TopIPsSince(ctx context.Context, arg TopIPsSinceParams) ([]TopIPsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, topIPsSince, arg.Ts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopIPsSinceRow
	for rows.Next() {
		var i TopIPsSinceRow
		if err := rows.Scan(&i.ClientIp, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topReferrersSince = `-- name: TopReferrersSince :many
SELECT referer, COUNT(*) AS cnt
FROM requests WHERE ts >= ? AND referer != ''
GROUP BY referer ORDER BY cnt DESC LIMIT ?
`

type TopReferrersSinceParams struct {
	Ts    time.Time `json:"ts"`
	Limit int64     `json:"limit"`
}

type TopReferrersSinceRow struct {
	Referer string `json:"referer"`
	Cnt     int64  `json:"cnt"`
}

func (q *Queries) TopReferrersSince(ctx context.Context, arg TopReferrersSinceParams) ([]TopReferrersSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, topReferrersSince, arg.Ts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopReferrersSinceRow
	for rows.Next() {
		var i TopReferrersSinceRow
		if err := rows.Scan(&i.Referer, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topUserAgentsSince = `-- name: TopUserAgentsSince :many
SELECT user_agent, COUNT(*) AS cnt, MAX(is_bot) AS is_bot
FROM requests WHERE ts >= ?
GROUP BY user_agent ORDER BY cnt DESC LIMIT ?
`

type TopUserAgentsSinceParams struct {
	Ts    time.Time `json:"ts"`
	Limit int64     `json:"limit"`
}

type TopUserAgentsSinceRow struct {
	UserAgent string      `json:"user_agent"`
	Cnt       int64       `json:"cnt"`
	IsBot     interface{} `json:"is_bot"`
}

func (q *Queries) TopUserAgentsSince(ctx context.Context, arg TopUserAgentsSinceParams) ([]TopUserAgentsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, topUserAgentsSince, arg.Ts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopUserAgentsSinceRow
	for rows.Next() {
		var i TopUserAgentsSinceRow
		if err := rows.Scan(&i.UserAgent, &i.Cnt, &i.IsBot); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
