// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const dailySummary = `-- name: DailySummary :many
SELECT
    date(ts) AS day,
    COUNT(*) AS total,
    SUM(CASE WHEN is_bot = 1 THEN 1 ELSE 0 END) AS bots,
    COUNT(DISTINCT client_ip) AS unique_ips,
    SUM(CASE WHEN status >= 400 THEN 1 ELSE 0 END) AS errors,
    ROUND(AVG(duration_ms), 1) AS avg_duration_ms
FROM requests
WHERE ts >= ?
GROUP BY day ORDER BY day DESC
`

type DailySummaryRow struct {
	Day           interface{}     `json:"day"`
	Total         int64           `json:"total"`
	Bots          sql.NullFloat64 `json:"bots"`
	UniqueIps     int64           `json:"unique_ips"`
	Errors        sql.NullFloat64 `json:"errors"`
	AvgDurationMs float64         `json:"avg_duration_ms"`
}

func (q *Queries) DailySummary(ctx context.Context, ts time.Time) ([]DailySummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, dailySummary, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailySummaryRow
	for rows.Next() {
		var i DailySummaryRow
		if err := rows.Scan(
			&i.Day,
			&i.Total,
			&i.Bots,
			&i.UniqueIps,
			&i.Errors,
			&i.AvgDurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hourlyRequestCounts = `-- name: HourlyRequestCounts :many
SELECT strftime('%Y-%m-%d %H:00', ts) AS hour, COUNT(*) AS cnt
FROM requests
WHERE ts >= ?
GROUP BY hour ORDER BY hour
`

type HourlyRequestCountsRow struct {
	Hour interface{} `json:"hour"`
	Cnt  int64       `json:"cnt"`
}

func (q *Queries) HourlyRequestCounts(ctx context.Context, ts time.Time) ([]HourlyRequestCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, hourlyRequestCounts, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HourlyRequestCountsRow
	for rows.Next() {
		var i HourlyRequestCountsRow
		if err := rows.Scan(&i.Hour, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hourlyRequestCountsByHost = `-- name: HourlyRequestCountsByHost :many
SELECT strftime('%Y-%m-%d %H:00', ts) AS hour, COUNT(*) AS cnt
FROM requests
WHERE ts >= ?1 AND (?2 = '' OR host = ?2)
GROUP BY hour ORDER BY hour
`

type HourlyRequestCountsByHostParams struct {
	Since      time.Time   `json:"since"`
	HostFilter interface{} `json:"host_filter"`
}

type HourlyRequestCountsByHostRow struct {
	Hour interface{} `json:"hour"`
	Cnt  int64       `json:"cnt"`
}

func (q *Queries) HourlyRequestCountsByHost(ctx context.Context, arg HourlyRequestCountsByHostParams) ([]HourlyRequestCountsByHostRow, error) {
	rows, err := q.db.QueryContext(ctx, hourlyRequestCountsByHost, arg.Since, arg.HostFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HourlyRequestCountsByHostRow
	for rows.Next() {
		var i HourlyRequestCountsByHostRow
		if err := rows.Scan(&i.Hour, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRequests = `-- name: SearchRequests :many
SELECT id, ts, host, client_ip, method, uri, status, size, user_agent, duration_ms, is_bot
FROM requests
WHERE (?1 = '' OR host = ?1)
  AND (?2 = '' OR client_ip = ?2)
  AND (?3 = 0 OR status = ?3)
  AND (?4 = '' OR user_agent LIKE '%' || ?4 || '%')
  AND ts >= ?5 AND ts <= ?6
ORDER BY id DESC
LIMIT ?8 OFFSET ?7
`

type SearchRequestsParams struct {
	HostFilter   interface{} `json:"host_filter"`
	IpFilter     interface{} `json:"ip_filter"`
	StatusFilter interface{} `json:"status_filter"`
	UaFilter     interface{} `json:"ua_filter"`
	FromTs       time.Time   `json:"from_ts"`
	ToTs         time.Time   `json:"to_ts"`
	Off          int64       `json:"off"`
	Lim          int64       `json:"lim"`
}

func (q *Queries) SearchRequests(ctx context.Context, arg SearchRequestsParams) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, searchRequests,
		arg.HostFilter,
		arg.IpFilter,
		arg.StatusFilter,
		arg.UaFilter,
		arg.FromTs,
		arg.ToTs,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Host,
			&i.ClientIp,
			&i.Method,
			&i.Uri,
			&i.Status,
			&i.Size,
			&i.UserAgent,
			&i.DurationMs,
			&i.IsBot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
