// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const dailySummary = `-- name: DailySummary :many
SELECT day, total, bots, unique_ips, errors, avg_duration AS avg_duration_ms, bytes AS total_bytes
FROM daily_stats
WHERE day >= ?1
ORDER BY day DESC
`

type DailySummaryRow struct {
	Day           string  `json:"day"`
	Total         int64   `json:"total"`
	Bots          int64   `json:"bots"`
	UniqueIps     int64   `json:"unique_ips"`
	Errors        int64   `json:"errors"`
	AvgDurationMs float64 `json:"avg_duration_ms"`
	TotalBytes    int64   `json:"total_bytes"`
}

// Reads the rollup, not raw rows. Previously this recomputed six aggregates
// (including a COUNT DISTINCT) over a 30-day partition of `requests` on every
// /history load and every /partials/daily poll.
func (q *Queries) DailySummary(ctx context.Context, fromDay string) ([]DailySummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, dailySummary, fromDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailySummaryRow
	for rows.Next() {
		var i DailySummaryRow
		if err := rows.Scan(
			&i.Day,
			&i.Total,
			&i.Bots,
			&i.UniqueIps,
			&i.Errors,
			&i.AvgDurationMs,
			&i.TotalBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const daysMissingFromDailyStats = `-- name: DaysMissingFromDailyStats :many
SELECT DISTINCT date(ts) AS day
FROM requests
WHERE date(ts) NOT IN (SELECT day FROM daily_stats)
ORDER BY day
`

// Days present in raw `requests` but not yet rolled up. Drives the backfill and
// catches any day missed while the process was down.
func (q *Queries) DaysMissingFromDailyStats(ctx context.Context) ([]interface{}, error) {
	rows, err := q.db.QueryContext(ctx, daysMissingFromDailyStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var day interface{}
		if err := rows.Scan(&day); err != nil {
			return nil, err
		}
		items = append(items, day)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteDailyStatsBefore = `-- name: DeleteDailyStatsBefore :exec
DELETE FROM daily_stats WHERE day < ?1
`

func (q *Queries) DeleteDailyStatsBefore(ctx context.Context, cutoffDay string) error {
	_, err := q.db.ExecContext(ctx, deleteDailyStatsBefore, cutoffDay)
	return err
}

const hourlyBandwidth = `-- name: HourlyBandwidth :many
SELECT strftime('%Y-%m-%d %H:00', ts) AS hour, SUM(size) AS total_bytes, COUNT(*) AS cnt
FROM requests
WHERE ts >= ?1 AND (?2 = '' OR host = ?2)
GROUP BY hour ORDER BY hour
`

type HourlyBandwidthParams struct {
	Since      time.Time   `json:"since"`
	HostFilter interface{} `json:"host_filter"`
}

type HourlyBandwidthRow struct {
	Hour       interface{}     `json:"hour"`
	TotalBytes sql.NullFloat64 `json:"total_bytes"`
	Cnt        int64           `json:"cnt"`
}

func (q *Queries) HourlyBandwidth(ctx context.Context, arg HourlyBandwidthParams) ([]HourlyBandwidthRow, error) {
	rows, err := q.db.QueryContext(ctx, hourlyBandwidth, arg.Since, arg.HostFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HourlyBandwidthRow
	for rows.Next() {
		var i HourlyBandwidthRow
		if err := rows.Scan(&i.Hour, &i.TotalBytes, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hourlyDurations = `-- name: HourlyDurations :many
SELECT strftime('%Y-%m-%d %H:00', ts) AS hour, duration_ms
FROM requests
WHERE ts >= ?1 AND (?2 = '' OR host = ?2)
ORDER BY hour, duration_ms
`

type HourlyDurationsParams struct {
	Since      time.Time   `json:"since"`
	HostFilter interface{} `json:"host_filter"`
}

type HourlyDurationsRow struct {
	Hour       interface{} `json:"hour"`
	DurationMs float64     `json:"duration_ms"`
}

func (q *Queries) HourlyDurations(ctx context.Context, arg HourlyDurationsParams) ([]HourlyDurationsRow, error) {
	rows, err := q.db.QueryContext(ctx, hourlyDurations, arg.Since, arg.HostFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HourlyDurationsRow
	for rows.Next() {
		var i HourlyDurationsRow
		if err := rows.Scan(&i.Hour, &i.DurationMs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hourlyRequestCounts = `-- name: HourlyRequestCounts :many
SELECT strftime('%Y-%m-%d %H:00', ts) AS hour, COUNT(*) AS cnt
FROM requests
WHERE ts >= ?
GROUP BY hour ORDER BY hour
`

type HourlyRequestCountsRow struct {
	Hour interface{} `json:"hour"`
	Cnt  int64       `json:"cnt"`
}

func (q *Queries) HourlyRequestCounts(ctx context.Context, ts time.Time) ([]HourlyRequestCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, hourlyRequestCounts, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HourlyRequestCountsRow
	for rows.Next() {
		var i HourlyRequestCountsRow
		if err := rows.Scan(&i.Hour, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hourlyRequestCountsByHost = `-- name: HourlyRequestCountsByHost :many
SELECT strftime('%Y-%m-%d %H:00', ts) AS hour, COUNT(*) AS cnt
FROM requests
WHERE ts >= ?1 AND (?2 = '' OR host = ?2)
GROUP BY hour ORDER BY hour
`

type HourlyRequestCountsByHostParams struct {
	Since      time.Time   `json:"since"`
	HostFilter interface{} `json:"host_filter"`
}

type HourlyRequestCountsByHostRow struct {
	Hour interface{} `json:"hour"`
	Cnt  int64       `json:"cnt"`
}

func (q *Queries) HourlyRequestCountsByHost(ctx context.Context, arg HourlyRequestCountsByHostParams) ([]HourlyRequestCountsByHostRow, error) {
	rows, err := q.db.QueryContext(ctx, hourlyRequestCountsByHost, arg.Since, arg.HostFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HourlyRequestCountsByHostRow
	for rows.Next() {
		var i HourlyRequestCountsByHostRow
		if err := rows.Scan(&i.Hour, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const iPReputationData = `-- name: IPReputationData :many
SELECT
    client_ip,
    COUNT(*) AS total,
    SUM(CASE WHEN status >= 400 AND status < 500 THEN 1 ELSE 0 END) AS count_4xx,
    SUM(CASE WHEN is_bot = 1 THEN 1 ELSE 0 END) AS bot_count,
    MIN(ts) AS first_seen,
    MAX(ts) AS last_seen
FROM requests
WHERE ts >= ?
GROUP BY client_ip
HAVING total >= 3
ORDER BY total DESC
LIMIT ?
`

type IPReputationDataParams struct {
	Ts    time.Time `json:"ts"`
	Limit int64     `json:"limit"`
}

type IPReputationDataRow struct {
	ClientIp  string          `json:"client_ip"`
	Total     int64           `json:"total"`
	Count4xx  sql.NullFloat64 `json:"count_4xx"`
	BotCount  sql.NullFloat64 `json:"bot_count"`
	FirstSeen interface{}     `json:"first_seen"`
	LastSeen  interface{}     `json:"last_seen"`
}

func (q *Queries) IPReputationData(ctx context.Context, arg IPReputationDataParams) ([]IPReputationDataRow, error) {
	rows, err := q.db.QueryContext(ctx, iPReputationData, arg.Ts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IPReputationDataRow
	for rows.Next() {
		var i IPReputationDataRow
		if err := rows.Scan(
			&i.ClientIp,
			&i.Total,
			&i.Count4xx,
			&i.BotCount,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const minutelyRequestCountsByHost = `-- name: MinutelyRequestCountsByHost :many
SELECT host, strftime('%Y-%m-%d %H:%M', ts) AS minute, COUNT(*) AS cnt
FROM requests
WHERE ts >= ?
GROUP BY host, minute
ORDER BY host, minute
`

type MinutelyRequestCountsByHostRow struct {
	Host   string      `json:"host"`
	Minute interface{} `json:"minute"`
	Cnt    int64       `json:"cnt"`
}

func (q *Queries) MinutelyRequestCountsByHost(ctx context.Context, ts time.Time) ([]MinutelyRequestCountsByHostRow, error) {
	rows, err := q.db.QueryContext(ctx, minutelyRequestCountsByHost, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MinutelyRequestCountsByHostRow
	for rows.Next() {
		var i MinutelyRequestCountsByHostRow
		if err := rows.Scan(&i.Host, &i.Minute, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollupDailyStats = `-- name: RollupDailyStats :exec
INSERT INTO daily_stats (day, total, bots, unique_ips, errors, avg_duration, bytes)
SELECT
    date(ts),
    COUNT(*),
    SUM(CASE WHEN is_bot = 1 THEN 1 ELSE 0 END),
    COUNT(DISTINCT client_ip),
    SUM(CASE WHEN status >= 400 THEN 1 ELSE 0 END),
    COALESCE(ROUND(AVG(duration_ms), 1), 0),
    COALESCE(SUM(size), 0)
FROM requests
WHERE date(ts) = CAST(?1 AS TEXT)
GROUP BY date(ts)
ON CONFLICT(day) DO UPDATE SET
    total = excluded.total, bots = excluded.bots, unique_ips = excluded.unique_ips,
    errors = excluded.errors, avg_duration = excluded.avg_duration, bytes = excluded.bytes
`

// Recomputes one day from raw. Called for today and yesterday on each rollup
// tick (yesterday so the final late-arriving rows are folded in), and for every
// uncovered day during backfill. UPSERT so re-running is idempotent.
func (q *Queries) RollupDailyStats(ctx context.Context, day string) error {
	_, err := q.db.ExecContext(ctx, rollupDailyStats, day)
	return err
}

const searchRequests = `-- name: SearchRequests :many
SELECT id, ts, host, client_ip, method, uri, status, size, user_agent, duration_ms, is_bot, referer
FROM requests
WHERE (?1 = '' OR host = ?1)
  AND (?2 = '' OR client_ip = ?2)
  AND (?3 = 0
       OR (?3 < 10 AND status / 100 = ?3)
       OR (?3 >= 10 AND status = ?3))
  AND (?4 = '' OR user_agent LIKE '%' || ?4 || '%')
  AND ts >= ?5 AND ts <= ?6
ORDER BY id DESC
LIMIT ?8 OFFSET ?7
`

type SearchRequestsParams struct {
	HostFilter   interface{} `json:"host_filter"`
	IpFilter     interface{} `json:"ip_filter"`
	StatusFilter interface{} `json:"status_filter"`
	UaFilter     interface{} `json:"ua_filter"`
	FromTs       time.Time   `json:"from_ts"`
	ToTs         time.Time   `json:"to_ts"`
	Off          int64       `json:"off"`
	Lim          int64       `json:"lim"`
}

type SearchRequestsRow struct {
	ID         int64     `json:"id"`
	Ts         time.Time `json:"ts"`
	Host       string    `json:"host"`
	ClientIp   string    `json:"client_ip"`
	Method     string    `json:"method"`
	Uri        string    `json:"uri"`
	Status     int64     `json:"status"`
	Size       int64     `json:"size"`
	UserAgent  string    `json:"user_agent"`
	DurationMs float64   `json:"duration_ms"`
	IsBot      int64     `json:"is_bot"`
	Referer    string    `json:"referer"`
}

func (q *Queries) SearchRequests(ctx context.Context, arg SearchRequestsParams) ([]SearchRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchRequests,
		arg.HostFilter,
		arg.IpFilter,
		arg.StatusFilter,
		arg.UaFilter,
		arg.FromTs,
		arg.ToTs,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchRequestsRow
	for rows.Next() {
		var i SearchRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Host,
			&i.ClientIp,
			&i.Method,
			&i.Uri,
			&i.Status,
			&i.Size,
			&i.UserAgent,
			&i.DurationMs,
			&i.IsBot,
			&i.Referer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRequestsExport = `-- name: SearchRequestsExport :many
SELECT id, ts, host, client_ip, method, uri, status, size, user_agent, duration_ms, is_bot, referer
FROM requests
WHERE (?1 = '' OR host = ?1)
  AND (?2 = '' OR client_ip = ?2)
  AND (?3 = 0
       OR (?3 < 10 AND status / 100 = ?3)
       OR (?3 >= 10 AND status = ?3))
  AND (?4 = '' OR user_agent LIKE '%' || ?4 || '%')
  AND ts >= ?5 AND ts <= ?6
ORDER BY id DESC
LIMIT 10000
`

type SearchRequestsExportParams struct {
	HostFilter   interface{} `json:"host_filter"`
	IpFilter     interface{} `json:"ip_filter"`
	StatusFilter interface{} `json:"status_filter"`
	UaFilter     interface{} `json:"ua_filter"`
	FromTs       time.Time   `json:"from_ts"`
	ToTs         time.Time   `json:"to_ts"`
}

type SearchRequestsExportRow struct {
	ID         int64     `json:"id"`
	Ts         time.Time `json:"ts"`
	Host       string    `json:"host"`
	ClientIp   string    `json:"client_ip"`
	Method     string    `json:"method"`
	Uri        string    `json:"uri"`
	Status     int64     `json:"status"`
	Size       int64     `json:"size"`
	UserAgent  string    `json:"user_agent"`
	DurationMs float64   `json:"duration_ms"`
	IsBot      int64     `json:"is_bot"`
	Referer    string    `json:"referer"`
}

func (q *Queries) SearchRequestsExport(ctx context.Context, arg SearchRequestsExportParams) ([]SearchRequestsExportRow, error) {
	rows, err := q.db.QueryContext(ctx, searchRequestsExport,
		arg.HostFilter,
		arg.IpFilter,
		arg.StatusFilter,
		arg.UaFilter,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchRequestsExportRow
	for rows.Next() {
		var i SearchRequestsExportRow
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Host,
			&i.ClientIp,
			&i.Method,
			&i.Uri,
			&i.Status,
			&i.Size,
			&i.UserAgent,
			&i.DurationMs,
			&i.IsBot,
			&i.Referer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topCountriesSince = `-- name: TopCountriesSince :many
SELECT country, COUNT(*) AS cnt
FROM requests WHERE ts >= ? AND country != ''
GROUP BY country ORDER BY cnt DESC LIMIT ?
`

type TopCountriesSinceParams struct {
	Ts    time.Time `json:"ts"`
	Limit int64     `json:"limit"`
}

type TopCountriesSinceRow struct {
	Country string `json:"country"`
	Cnt     int64  `json:"cnt"`
}

func (q *Queries) TopCountriesSince(ctx context.Context, arg TopCountriesSinceParams) ([]TopCountriesSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, topCountriesSince, arg.Ts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopCountriesSinceRow
	for rows.Next() {
		var i TopCountriesSinceRow
		if err := rows.Scan(&i.Country, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
