// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uptime.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const avgResponseTime = `-- name: AvgResponseTime :one
SELECT COALESCE(ROUND(AVG(response_time_ms), 1), 0) AS avg_ms
FROM uptime_checks
WHERE target_id = ? AND ts >= ? AND error = ''
`

type AvgResponseTimeParams struct {
	TargetID int64     `json:"target_id"`
	Ts       time.Time `json:"ts"`
}

func (q *Queries) AvgResponseTime(ctx context.Context, arg AvgResponseTimeParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, avgResponseTime, arg.TargetID, arg.Ts)
	var avg_ms interface{}
	err := row.Scan(&avg_ms)
	return avg_ms, err
}

const createUptimeTarget = `-- name: CreateUptimeTarget :exec
INSERT INTO uptime_targets (name, url, interval_seconds, expected_status) VALUES (?, ?, ?, ?)
`

type CreateUptimeTargetParams struct {
	Name            string `json:"name"`
	Url             string `json:"url"`
	IntervalSeconds int64  `json:"interval_seconds"`
	ExpectedStatus  int64  `json:"expected_status"`
}

func (q *Queries) CreateUptimeTarget(ctx context.Context, arg CreateUptimeTargetParams) error {
	_, err := q.db.ExecContext(ctx, createUptimeTarget,
		arg.Name,
		arg.Url,
		arg.IntervalSeconds,
		arg.ExpectedStatus,
	)
	return err
}

const daysMissingFromUptimeDaily = `-- name: DaysMissingFromUptimeDaily :many
SELECT DISTINCT date(ts) AS day
FROM uptime_checks
WHERE date(ts) NOT IN (SELECT day FROM uptime_daily)
ORDER BY day
`

func (q *Queries) DaysMissingFromUptimeDaily(ctx context.Context) ([]interface{}, error) {
	rows, err := q.db.QueryContext(ctx, daysMissingFromUptimeDaily)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var day interface{}
		if err := rows.Scan(&day); err != nil {
			return nil, err
		}
		items = append(items, day)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteUptimeChecksBeforeBatch = `-- name: DeleteUptimeChecksBeforeBatch :execresult
DELETE FROM uptime_checks WHERE id IN (
    SELECT u.id FROM uptime_checks u WHERE u.ts < ?1 ORDER BY u.id LIMIT ?2
)
`

type DeleteUptimeChecksBeforeBatchParams struct {
	Cutoff    time.Time `json:"cutoff"`
	BatchSize int64     `json:"batch_size"`
}

func (q *Queries) DeleteUptimeChecksBeforeBatch(ctx context.Context, arg DeleteUptimeChecksBeforeBatchParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUptimeChecksBeforeBatch, arg.Cutoff, arg.BatchSize)
}

const deleteUptimeChecksForTarget = `-- name: DeleteUptimeChecksForTarget :exec
DELETE FROM uptime_checks WHERE target_id = ?
`

func (q *Queries) DeleteUptimeChecksForTarget(ctx context.Context, targetID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUptimeChecksForTarget, targetID)
	return err
}

const deleteUptimeDailyBefore = `-- name: DeleteUptimeDailyBefore :exec
DELETE FROM uptime_daily WHERE day < ?1
`

func (q *Queries) DeleteUptimeDailyBefore(ctx context.Context, cutoffDay string) error {
	_, err := q.db.ExecContext(ctx, deleteUptimeDailyBefore, cutoffDay)
	return err
}

const deleteUptimeDailyForTarget = `-- name: DeleteUptimeDailyForTarget :exec
DELETE FROM uptime_daily WHERE target_id = ?
`

func (q *Queries) DeleteUptimeDailyForTarget(ctx context.Context, targetID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUptimeDailyForTarget, targetID)
	return err
}

const deleteUptimeTarget = `-- name: DeleteUptimeTarget :exec
DELETE FROM uptime_targets WHERE id = ?
`

func (q *Queries) DeleteUptimeTarget(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUptimeTarget, id)
	return err
}

const getUptimeTarget = `-- name: GetUptimeTarget :one
SELECT id, name, url, interval_seconds, expected_status, enabled, created_at
FROM uptime_targets WHERE id = ?
`

func (q *Queries) GetUptimeTarget(ctx context.Context, id int64) (UptimeTarget, error) {
	row := q.db.QueryRowContext(ctx, getUptimeTarget, id)
	var i UptimeTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.IntervalSeconds,
		&i.ExpectedStatus,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const insertUptimeCheck = `-- name: InsertUptimeCheck :exec
INSERT INTO uptime_checks (target_id, ts, status, response_time_ms, error) VALUES (?, ?, ?, ?, ?)
`

type InsertUptimeCheckParams struct {
	TargetID       int64     `json:"target_id"`
	Ts             time.Time `json:"ts"`
	Status         int64     `json:"status"`
	ResponseTimeMs float64   `json:"response_time_ms"`
	Error          string    `json:"error"`
}

func (q *Queries) InsertUptimeCheck(ctx context.Context, arg InsertUptimeCheckParams) error {
	_, err := q.db.ExecContext(ctx, insertUptimeCheck,
		arg.TargetID,
		arg.Ts,
		arg.Status,
		arg.ResponseTimeMs,
		arg.Error,
	)
	return err
}

const listEnabledUptimeTargets = `-- name: ListEnabledUptimeTargets :many
SELECT id, name, url, interval_seconds, expected_status
FROM uptime_targets WHERE enabled = 1
`

type ListEnabledUptimeTargetsRow struct {
	ID              int64  `json:"id"`
	Name            string `json:"name"`
	Url             string `json:"url"`
	IntervalSeconds int64  `json:"interval_seconds"`
	ExpectedStatus  int64  `json:"expected_status"`
}

func (q *Queries) ListEnabledUptimeTargets(ctx context.Context) ([]ListEnabledUptimeTargetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledUptimeTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledUptimeTargetsRow
	for rows.Next() {
		var i ListEnabledUptimeTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.IntervalSeconds,
			&i.ExpectedStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUptimeTargets = `-- name: ListUptimeTargets :many
SELECT id, name, url, interval_seconds, expected_status, enabled, created_at
FROM uptime_targets ORDER BY name
`

func (q *Queries) ListUptimeTargets(ctx context.Context) ([]UptimeTarget, error) {
	rows, err := q.db.QueryContext(ctx, listUptimeTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UptimeTarget
	for rows.Next() {
		var i UptimeTarget
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.IntervalSeconds,
			&i.ExpectedStatus,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentUptimeChecks = `-- name: RecentUptimeChecks :many
SELECT id, target_id, ts, status, response_time_ms, error
FROM uptime_checks WHERE target_id = ? ORDER BY id DESC LIMIT ?
`

type RecentUptimeChecksParams struct {
	TargetID int64 `json:"target_id"`
	Limit    int64 `json:"limit"`
}

func (q *Queries) RecentUptimeChecks(ctx context.Context, arg RecentUptimeChecksParams) ([]UptimeCheck, error) {
	rows, err := q.db.QueryContext(ctx, recentUptimeChecks, arg.TargetID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UptimeCheck
	for rows.Next() {
		var i UptimeCheck
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.Ts,
			&i.Status,
			&i.ResponseTimeMs,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollupUptimeDaily = `-- name: RollupUptimeDaily :exec
INSERT INTO uptime_daily (target_id, day, checks, up_count, avg_response_ms, max_response_ms)
SELECT
    target_id,
    date(ts),
    COUNT(*),
    SUM(CASE WHEN error = '' THEN 1 ELSE 0 END),
    COALESCE(ROUND(AVG(CASE WHEN error = '' THEN response_time_ms END), 1), 0),
    COALESCE(MAX(CASE WHEN error = '' THEN response_time_ms END), 0)
FROM uptime_checks
WHERE ts >= CAST(?1 AS TEXT)
  AND ts < date(CAST(?1 AS TEXT), '+1 day')
GROUP BY target_id, date(ts)
ON CONFLICT(target_id, day) DO UPDATE SET
    checks = excluded.checks, up_count = excluded.up_count,
    avg_response_ms = excluded.avg_response_ms, max_response_ms = excluded.max_response_ms
`

// Half-open range, for the same reason as RollupDailyStats.
func (q *Queries) RollupUptimeDaily(ctx context.Context, day string) error {
	_, err := q.db.ExecContext(ctx, rollupUptimeDaily, day)
	return err
}

const toggleUptimeTarget = `-- name: ToggleUptimeTarget :exec
UPDATE uptime_targets SET enabled = CASE WHEN enabled = 0 THEN 1 ELSE 0 END WHERE id = ?
`

func (q *Queries) ToggleUptimeTarget(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, toggleUptimeTarget, id)
	return err
}

const updateUptimeTarget = `-- name: UpdateUptimeTarget :exec
UPDATE uptime_targets
SET name = ?, url = ?, interval_seconds = ?, expected_status = ?
WHERE id = ?
`

type UpdateUptimeTargetParams struct {
	Name            string `json:"name"`
	Url             string `json:"url"`
	IntervalSeconds int64  `json:"interval_seconds"`
	ExpectedStatus  int64  `json:"expected_status"`
	ID              int64  `json:"id"`
}

// Edits a target in place so its uptime_checks and uptime_daily history survive.
// Deleting and recreating would orphan both.
func (q *Queries) UpdateUptimeTarget(ctx context.Context, arg UpdateUptimeTargetParams) error {
	_, err := q.db.ExecContext(ctx, updateUptimeTarget,
		arg.Name,
		arg.Url,
		arg.IntervalSeconds,
		arg.ExpectedStatus,
		arg.ID,
	)
	return err
}

const uptimeChecksSince = `-- name: UptimeChecksSince :many
SELECT id, target_id, ts, status, response_time_ms, error
FROM uptime_checks
WHERE target_id = ?1 AND ts >= ?2
ORDER BY ts
`

type UptimeChecksSinceParams struct {
	TargetID int64     `json:"target_id"`
	Since    time.Time `json:"since"`
}

func (q *Queries) UptimeChecksSince(ctx context.Context, arg UptimeChecksSinceParams) ([]UptimeCheck, error) {
	rows, err := q.db.QueryContext(ctx, uptimeChecksSince, arg.TargetID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UptimeCheck
	for rows.Next() {
		var i UptimeCheck
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.Ts,
			&i.Status,
			&i.ResponseTimeMs,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uptimeDailySince = `-- name: UptimeDailySince :many
SELECT target_id, day, checks, up_count, avg_response_ms, max_response_ms
FROM uptime_daily
WHERE target_id = ?1 AND day >= ?2
ORDER BY day
`

type UptimeDailySinceParams struct {
	TargetID int64  `json:"target_id"`
	FromDay  string `json:"from_day"`
}

func (q *Queries) UptimeDailySince(ctx context.Context, arg UptimeDailySinceParams) ([]UptimeDaily, error) {
	rows, err := q.db.QueryContext(ctx, uptimeDailySince, arg.TargetID, arg.FromDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UptimeDaily
	for rows.Next() {
		var i UptimeDaily
		if err := rows.Scan(
			&i.TargetID,
			&i.Day,
			&i.Checks,
			&i.UpCount,
			&i.AvgResponseMs,
			&i.MaxResponseMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uptimePercentage = `-- name: UptimePercentage :one
SELECT
    COUNT(*) AS total,
    SUM(CASE WHEN status = ? THEN 1 ELSE 0 END) AS up_count
FROM uptime_checks
WHERE target_id = ? AND ts >= ?
`

type UptimePercentageParams struct {
	Status   int64     `json:"status"`
	TargetID int64     `json:"target_id"`
	Ts       time.Time `json:"ts"`
}

type UptimePercentageRow struct {
	Total   int64           `json:"total"`
	UpCount sql.NullFloat64 `json:"up_count"`
}

func (q *Queries) UptimePercentage(ctx context.Context, arg UptimePercentageParams) (UptimePercentageRow, error) {
	row := q.db.QueryRowContext(ctx, uptimePercentage, arg.Status, arg.TargetID, arg.Ts)
	var i UptimePercentageRow
	err := row.Scan(&i.Total, &i.UpCount)
	return i, err
}
