// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: uptime.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const avgResponseTime = `-- name: AvgResponseTime :one
SELECT COALESCE(ROUND(AVG(response_time_ms), 1), 0) AS avg_ms
FROM uptime_checks
WHERE target_id = ? AND ts >= ? AND error = ''
`

type AvgResponseTimeParams struct {
	TargetID int64     `json:"target_id"`
	Ts       time.Time `json:"ts"`
}

func (q *Queries) AvgResponseTime(ctx context.Context, arg AvgResponseTimeParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, avgResponseTime, arg.TargetID, arg.Ts)
	var avg_ms interface{}
	err := row.Scan(&avg_ms)
	return avg_ms, err
}

const createUptimeTarget = `-- name: CreateUptimeTarget :exec
INSERT INTO uptime_targets (name, url, interval_seconds, expected_status) VALUES (?, ?, ?, ?)
`

type CreateUptimeTargetParams struct {
	Name            string `json:"name"`
	Url             string `json:"url"`
	IntervalSeconds int64  `json:"interval_seconds"`
	ExpectedStatus  int64  `json:"expected_status"`
}

func (q *Queries) CreateUptimeTarget(ctx context.Context, arg CreateUptimeTargetParams) error {
	_, err := q.db.ExecContext(ctx, createUptimeTarget,
		arg.Name,
		arg.Url,
		arg.IntervalSeconds,
		arg.ExpectedStatus,
	)
	return err
}

const deleteUptimeChecksBefore = `-- name: DeleteUptimeChecksBefore :exec
DELETE FROM uptime_checks WHERE ts < ?
`

func (q *Queries) DeleteUptimeChecksBefore(ctx context.Context, ts time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteUptimeChecksBefore, ts)
	return err
}

const deleteUptimeTarget = `-- name: DeleteUptimeTarget :exec
DELETE FROM uptime_targets WHERE id = ?
`

func (q *Queries) DeleteUptimeTarget(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUptimeTarget, id)
	return err
}

const getUptimeTarget = `-- name: GetUptimeTarget :one
SELECT id, name, url, interval_seconds, expected_status, enabled, created_at
FROM uptime_targets WHERE id = ?
`

func (q *Queries) GetUptimeTarget(ctx context.Context, id int64) (UptimeTarget, error) {
	row := q.db.QueryRowContext(ctx, getUptimeTarget, id)
	var i UptimeTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.IntervalSeconds,
		&i.ExpectedStatus,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const insertUptimeCheck = `-- name: InsertUptimeCheck :exec
INSERT INTO uptime_checks (target_id, ts, status, response_time_ms, error) VALUES (?, ?, ?, ?, ?)
`

type InsertUptimeCheckParams struct {
	TargetID       int64     `json:"target_id"`
	Ts             time.Time `json:"ts"`
	Status         int64     `json:"status"`
	ResponseTimeMs float64   `json:"response_time_ms"`
	Error          string    `json:"error"`
}

func (q *Queries) InsertUptimeCheck(ctx context.Context, arg InsertUptimeCheckParams) error {
	_, err := q.db.ExecContext(ctx, insertUptimeCheck,
		arg.TargetID,
		arg.Ts,
		arg.Status,
		arg.ResponseTimeMs,
		arg.Error,
	)
	return err
}

const listEnabledUptimeTargets = `-- name: ListEnabledUptimeTargets :many
SELECT id, name, url, interval_seconds, expected_status
FROM uptime_targets WHERE enabled = 1
`

type ListEnabledUptimeTargetsRow struct {
	ID              int64  `json:"id"`
	Name            string `json:"name"`
	Url             string `json:"url"`
	IntervalSeconds int64  `json:"interval_seconds"`
	ExpectedStatus  int64  `json:"expected_status"`
}

func (q *Queries) ListEnabledUptimeTargets(ctx context.Context) ([]ListEnabledUptimeTargetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledUptimeTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledUptimeTargetsRow
	for rows.Next() {
		var i ListEnabledUptimeTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.IntervalSeconds,
			&i.ExpectedStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUptimeTargets = `-- name: ListUptimeTargets :many
SELECT id, name, url, interval_seconds, expected_status, enabled, created_at
FROM uptime_targets ORDER BY name
`

func (q *Queries) ListUptimeTargets(ctx context.Context) ([]UptimeTarget, error) {
	rows, err := q.db.QueryContext(ctx, listUptimeTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UptimeTarget
	for rows.Next() {
		var i UptimeTarget
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.IntervalSeconds,
			&i.ExpectedStatus,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentUptimeChecks = `-- name: RecentUptimeChecks :many
SELECT id, target_id, ts, status, response_time_ms, error, created_at
FROM uptime_checks WHERE target_id = ? ORDER BY id DESC LIMIT ?
`

type RecentUptimeChecksParams struct {
	TargetID int64 `json:"target_id"`
	Limit    int64 `json:"limit"`
}

func (q *Queries) RecentUptimeChecks(ctx context.Context, arg RecentUptimeChecksParams) ([]UptimeCheck, error) {
	rows, err := q.db.QueryContext(ctx, recentUptimeChecks, arg.TargetID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UptimeCheck
	for rows.Next() {
		var i UptimeCheck
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.Ts,
			&i.Status,
			&i.ResponseTimeMs,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleUptimeTarget = `-- name: ToggleUptimeTarget :exec
UPDATE uptime_targets SET enabled = CASE WHEN enabled = 0 THEN 1 ELSE 0 END WHERE id = ?
`

func (q *Queries) ToggleUptimeTarget(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, toggleUptimeTarget, id)
	return err
}

const uptimeChecksSince = `-- name: UptimeChecksSince :many
SELECT id, target_id, ts, status, response_time_ms, error, created_at
FROM uptime_checks
WHERE target_id = ?1 AND ts >= ?2
ORDER BY ts
`

type UptimeChecksSinceParams struct {
	TargetID int64     `json:"target_id"`
	Since    time.Time `json:"since"`
}

func (q *Queries) UptimeChecksSince(ctx context.Context, arg UptimeChecksSinceParams) ([]UptimeCheck, error) {
	rows, err := q.db.QueryContext(ctx, uptimeChecksSince, arg.TargetID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UptimeCheck
	for rows.Next() {
		var i UptimeCheck
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.Ts,
			&i.Status,
			&i.ResponseTimeMs,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uptimePercentage = `-- name: UptimePercentage :one
SELECT
    COUNT(*) AS total,
    SUM(CASE WHEN status = ? THEN 1 ELSE 0 END) AS up_count
FROM uptime_checks
WHERE target_id = ? AND ts >= ?
`

type UptimePercentageParams struct {
	Status   int64     `json:"status"`
	TargetID int64     `json:"target_id"`
	Ts       time.Time `json:"ts"`
}

type UptimePercentageRow struct {
	Total   int64           `json:"total"`
	UpCount sql.NullFloat64 `json:"up_count"`
}

func (q *Queries) UptimePercentage(ctx context.Context, arg UptimePercentageParams) (UptimePercentageRow, error) {
	row := q.db.QueryRowContext(ctx, uptimePercentage, arg.Status, arg.TargetID, arg.Ts)
	var i UptimePercentageRow
	err := row.Scan(&i.Total, &i.UpCount)
	return i, err
}
